service: skill-ventilatore

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-alexa-skills

provider:
  name: aws
  runtime: nodejs16.x
  profile: <YOUR PROFILE>
  memorySize: 256
  stage: ${opt:stage}
  region: eu-west-1
  versionFunctions: false
  iam:
    role: 
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/FanSkillTable
          
custom:
  bundle:
    linting: false
    esbuild: true
  alexa: 
    vendorId: ${file(./priv_config.yml):vendorId}
    skills:
      - id: ${file(./config.yml):skillId}
        manifest:
          apis:
            custom:
              endpoint:
                uri: 'arn:aws:lambda:eu-west-1:{AWS::AccountId}:function:${self:service}-${self:provider.stage}'
              interfaces: []
              protocolVersion: '3'
          manifestVersion: '1.0'

functions:
  index:
    name: ${self:service}-${self:provider.stage}
    handler: index.handler
    events:
      - alexaSmartHome: ${file(./config.yml):skillId}

resources:
  Resources:
    FanSkill:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FanSkillTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ItemId
            AttributeType: S
        KeySchema:
          - AttributeName: ItemId
            KeyType: HASH
